### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by arnalll** [djearthquake/amxx#4]
hi, thanx for your work in this plugin.
the issue : i wasnt able to test it since at least lightning.spr is not present and so server crash.
also i had a warning while compiling that a symbol is never used "wpnid" 

best regards

**Comment by djearthquake** [comment]
The sprite should be in the valve directory stock. I haven't seen that happen in years. What version of Amxx are you using? That warning will go away now on newer copies of script. That was from when I added compass to Day of Defeat knifes and spade.

**Comment by arnalll** [comment]
hi, thanks again, there was a typo issue in the name of the spr, i use amxx 1.10,
but wih last code no more warning.
Now MOTD appears and say invalid Api key, will look later.

have a nice day

**Comment by djearthquake** [comment]
Typo on the file name or the script and how can you be so sure?
https://www.17buddies.rocks/17b2/View/Map/82113/yardrats_halloween.html is where the sprite came from.
![image](https://user-images.githubusercontent.com/6540695/184541406-0093e610-5ed4-406d-b064-dd70936d7b0c.png)

**Comment by djearthquake** [comment]
Sprite was repacked last week. Source given

**Comment by arnalll** [comment]
Thanks again, well i m at work now btw , when i ve said the typo issue i was refering to the 1st answer you gave to me i saw in e-mail that the sprite was in half life valve folder. there is one sprite named lghtning.spr... nevermind.  i will test  this week end with proper api key. 
my server is a DoD one and as far i see time of the day is working as expected, only issue, but without real api key working, is when i look at the sky a messy thing appear.

btw grat work

**Comment by arnalll** [comment]
oh it may be impossible but instead of using TGA's for the sky why not using models? Some maps (very few) have dynamic skyes made by models, "clouds moving etc..."
