### ISSUE TITLE
zero_round.sma

### ISSUE THREAD

**Issue by arkprocession** [djearthquake/amxx#8]
Can this plugin instead of roundtimer be 0 be a specific time?
Looking for a working workaround for this:
https://github.com/mlibre2/pawnamxx/blob/main/scripting/bot_freeze.sma

The plugin won't dynamically update the bot_freeze cvar if changed midgame, weird.
Also need like 2 mapchanges it's very inconsistent.

**Comment by djearthquake** [comment]
That is a forum request not an issue with Zero Round or anything here.
